fix(ui): UI cleanup
Sage-Bionetworks/sage-monorepo pull request #1465
Opened 2023-04-11 06:00 UTC by vpchung

Closes #1464 and closes #1450.  Using #1464 as a guide, this PR features UI cleanup for the "Must have" and "Should have".  The "Could have" are dependent on #1360, #1351, #1454, and so will not be implemented now.

![ui-cleanup](https://user-images.githubusercontent.com/9377970/231370858-3704db40-2084-4c49-b825-7128f330e3ea.gif)

> **Note** During this exercise, I noticed we also need to do a cleanup with the SCSS sheets as well (saving that for another PR).

2023-04-14 16:46 UTC, rrchai requested changes

2023-04-14 16:46 UTC, rrchai commented on libs/openchallenges/ui/src/lib/challenge-card/challenge-card.component.html
> +        Some incentive
Can you use `{{ challenge.incentives }}` instead? You might need some adjustment since `incentives` is a lowercased array.

2023-04-17 19:02 UTC, vpchung commented
Thank you for the feedback, all.  Here are some updates to the Meet the Team page and challenge cards:

### Meet the Team
Image heights are now kept consistent across team members:

![Screen Shot 2023-04-17 at 11 57 44 AM](https://user-images.githubusercontent.com/9377970/232584731-3a38be3b-f884-4392-9184-fa206ba7e208.png)

### Challenge card incentives
Incentives are now listed on the cards, where challenges with no incentives will list "No incentives listed":

![Screen Shot 2023-04-17 at 11 57 33 AM](https://user-images.githubusercontent.com/9377970/232584771-1939c6c0-0907-47f4-ae85-2423031f9cba.png)

2023-04-25 21:42 UTC, tschaffter approved these changes
Fantastic PR!

2023-04-25 21:42 UTC, merged