fix(property): Allow user/data curator to specify the avatar initials for organizations
Sage-Bionetworks/sage-monorepo pull request #1504
Opened 2023-05-04 20:55 UTC by mdsage1

Fixes #1481

2023-05-04 22:08 UTC, tschaffter requested changes
This is a great start. See the comments I left.

There is one more file that should be updated in the org service, see `model/entity/OrganizationEntity.java`.

2023-05-04 22:08 UTC, tschaffter commented on apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.1__insert_temp_data.sql
> +    challenge_count.
```suggestion
    challenge_count,
```

2023-05-04 22:08 UTC, tschaffter commented on libs/openchallenges/api-description/src/components/schemas/Organization.yaml
> +  - acronym
I would make this property optional as not all orgs may have an acronym.

2023-05-04 22:08 UTC, tschaffter commented on apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
> -  PRIMARY KEY (`id`),
Does this line need to be removed?

2023-05-04 22:08 UTC, tschaffter commented on apps/openchallenges/organization-service/src/main/resources/db/migration/V1.0.0__create_tables.sql
The new property should be added to the table `organization`

2023-05-04 22:10 UTC, tschaffter commented
@mdsage1 In the Original Post (OP), could you add a section named "Preview" that shows an example of Organization object returned by the organization service to illustrate this contribution?

2023-05-04 22:59 UTC, mdsage1 commented
The VALUES have not been updated in the INSERT INTO organization query. They will be updated soon.

2023-05-05 16:23 UTC, tschaffter commented
@mdsage1 The current snippet of code in the section `Preview` is not required because reviewers can see these changes under the tab `Files changed`. What I suggested was to show the JSON response returned by the organization service. This proves that the implementation works. You can get this response from the Swagger UI or from the file `requests.http` that lives in the project folder of the microservices.

2023-05-08 21:30 UTC, mdsage1 commented
The requested change has been implemented and pushed to this repo

2023-05-08 21:34 UTC, merged