fix(ui): home UI updates
Sage-Bionetworks/sage-monorepo pull request #1536
Opened 2023-05-11 23:54 UTC by vpchung

## Changelog

Other UI improvements to the home page, including:

* replace mock Featured Challenge cards with real ones (3 recently opened) - similar to #1533
* switch "Featured Challenge" section with "Discover Organizations" (makes more sense)
* link organizers to our [Contribution google sheet](https://docs.google.com/spreadsheets/d/1-3LO7h_JJf6rnEBvVJWjDD4FBmHCu-oiBNlxvSSnkwo/edit#gid=484902792)

## Preview
![home](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/2ef6e37c-bc3f-4e49-82a9-c42f39a3a4ec)

## Note

This branch was built off of my `issue-1533` branch, so this PR should be merged after #1535

2023-05-11 23:58 UTC, vpchung commented
@tschaffter okay, I _swear_ this will be my last UI fix for the private preview!

2023-05-12 17:45 UTC, vpchung commented
## Preview of latest changes

#### Discover Organizations

![Screen Shot 2023-05-12 at 10 44 05 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ec631b4e-302b-4c18-98c6-eed648665136)

#### Sponsors List

![Screen Shot 2023-05-12 at 10 44 11 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4d4aa3a8-8e5b-4cf6-b321-3e173828fadb)

2023-05-12 18:00 UTC, tschaffter requested changes

2023-05-12 21:06 UTC, tschaffter commented
I pushed the following changes:

- Merged `main` into this branch
- The sponsor logos are downloaded with height=140px (instead of the original images)
- Added the property `title` to the sponsor logos, in particular to show "Sage Bionetworks" when the cursor is hover our logo

2023-05-12 21:07 UTC, tschaffter approved these changes

2023-05-12 21:10 UTC, merged