Feature update mocked endpoints
Sage-Bionetworks/sage-monorepo pull request #1817
Opened 2023-07-19 18:41 UTC by andrewelamb

fixes [fds-688](https://sagebionetworks.jira.com/browse/FDS-688)

2023-07-20 01:37 UTC, tschaffter commented
@andrewelamb There is one check that fails and needs to be fixed before the PR can be reviewed.

2023-07-21 13:20 UTC, tschaffter commented
Unit and integration tests should mock calls to external services like Synapse, thus eliminating the need for the CI workflow to depend on secrets.

2023-07-22 03:09 UTC, tschaffter commented
@andrewelamb Congrats on fixing the tests of your first Sage Monorepo PR! 🎉 

I see that the task that build images failed because of OC projects. As mentioned above, updating this feature branch with the content of `main` should remove the OC projects from the list of `affected` projects.

2023-07-24 13:09 UTC, tschaffter commented
The CI workflow is running out of storage space because of the numerous affected projects.

```console
...
    [creator]     Adding label 'io.buildpacks.build.metadata'
    [creator]     Adding label 'io.buildpacks.project.metadata'
    [creator]     Adding label 'org.springframework.boot.version'
    [creator]     Setting default process type 'web'
    [creator]     Saving ghcr.io/sage-bionetworks/openchallenges-challenge-service-base:local...
    [creator]     ERROR: failed to export: saving image: fetching base layers: write /tmp/imgutil.local.image.2749701756/22bbaf1fa50dced77ae49a3be9119a74802577036986acf544fc44047f0abbe8/layer.tar: no space left on device
```

@andrewelamb This is a general issue that I will investigate over the week. Meanwhile, updating this feature branch with `main` should remove all the OC projects from the list of affected projects. The smaller number of affected projects will also speedup the execution of the workflow.

2023-07-24 16:55 UTC, tschaffter approved these changes
LGTM

2023-07-24 17:49 UTC, andrewelamb commented
@linglp @milen-sage Did you want to take a look before I merge?

2023-07-24 18:11 UTC, milen-sage approved these changes
Thanks @andrewelamb ! The PR provides a good overview of the overall structure, and that looks good to me. I'll defer to @linglp on reviewing the REST API logic in more detail, but that can happen later once its merged, too. 

I'm assuming this PR is large because is building up the codebase and in the future PRs would be scoped to smaller piece of code?

2023-07-24 18:15 UTC, andrewelamb commented
@milen-sage to a degree. The schema is spread across many files, so if you add an endpoint you will likely have to add/change several files. On the other hand, much of this is automatically generated so those wouldn't have to be checked during a PR.

2023-07-25 16:58 UTC, linglp requested changes
I think this PR should really be split into two or even three. For a big PR like this, I would appreciate if there's a more detailed description of what gets changed and what gets added. Here's a summary that I think could be added to PR description: 

## changelog
* Changed path of mock endpoint from `storages/projects/{@projectId}/datasets` to  `/assetTypes/{assetType}/assetViews/{assetViewId}/projects/{projectId}/datasets`
* Added mock implementation of `/assetTypes/{assetType}/assetViews/{assetViewId}/projects/{projectId}/datasets`
* Changed path of endpoint from `storage/asset-views/{assetView}/projects/{projectId}/manifests` to `assetTypes/@{assetType}/assetViews/@{assetViewId}/projects/@{projectId}/manifests.yaml`
* Added asset type as a parameter in the two endpoints above and organized storage resources under asset types 
* Updated assetView to assetViewId
* Changed definition of datasetId and manifest (see Dataset.yaml and Manifest.yaml) 
* Added mypy, black, pylint
* Added tests for handing erros 401, 403, 500

2023-07-25 17:04 UTC, andrewelamb commented on apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
> +        msg = f"{asset_type} is not an allowed value: [{list(asset_type_dict.keys())}]"
when you do dict.get("key") if they key isn't in the dict, None is returned.

2023-07-25 17:12 UTC, andrewelamb commented on libs/schematic/api-description/src/components/schemas/Manifest.yaml
> +  datasetId:
The current storage/projects/manifests endpoint, which this replaces, returns those things so I'm returning them here as well.

2023-07-25 17:24 UTC, andrewelamb commented on apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
> +    datasets = [Dataset(id=item[1][0], name=item[1][1]) for item in dataset_tuples]
Yes, you are correct I'm fixing this and adding a test to catch this.

2023-07-25 17:29 UTC, andrewelamb commented on libs/schematic/api-description/src/components/schemas/Manifest.yaml
> +  datasetId:
Oh also schemtic db  uses storage/projects/manifests, and makes use of the component name.

2023-07-25 18:32 UTC, linglp commented on apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
> +        msg = f"{asset_type} is not an allowed value: [{list(asset_type_dict.keys())}]"
Oh I see it now. Thanks.

2023-07-25 18:37 UTC, linglp commented on libs/schematic/api-description/src/components/schemas/Manifest.yaml
> +  datasetId:
I just tried using `storage/project/manifest` endpoint locally, and it returned: 
```
[
  [
    [
      "syn30988361",
      "TestFolder"
    ],
    [
      "syn30988380",
      "synapse_storage_manifest (2).csv"
    ],
    [
      "Biospecimen",
      "Biospecimen"
    ]
  ]
]
```
I think based on this output, it returned manifest id, manifest name, and also component name? But it doesn't return `datasetId` and `datasetName`?

2023-07-25 18:44 UTC, andrewelamb commented on libs/schematic/api-description/src/components/schemas/Manifest.yaml
> +  datasetId:
"syn30988361",
 "TestFolder"

Those are the dataset id and name

2023-07-25 18:46 UTC, andrewelamb commented on libs/schematic/api-description/src/components/schemas/Manifest.yaml
> +  datasetId:
Yeah, here's what the schematic function returns:

```
 Returns: A list of datasets per project; metadata manifest Synapse ID for each dataset; and the corresponding schema component of the manifest
                 as a list of tuples, one for each manifest:
                    [
                        (
                            (datasetId, dataName),
                            (manifestId, manifestName),
                            (componentSchemaLabel, componentSchemaLabel) TODO: # get component name from schema
                        ),
                        ...
                    ]
```

2023-07-25 18:50 UTC, linglp commented on libs/schematic/api-description/src/components/schemas/Manifest.yaml
> +  datasetId:
Oh I see it now. Thanks for explaining.

2023-07-25 19:53 UTC, linglp commented
@andrewelamb I tried running your test locally, and it seems like that it is not working: 
I did: `poetry run pytest test_storage_controller_endpoints.py::TestDatasets::test_success`, and here's the output: 
```
    self.assertEqual(response.status_code, status_code, message)
E   AssertionError: 500 != 200 : Response body is : {
E     "detail": "[Errno 2] No such file or directory: '/workspaces/sage-monorepo/apps/schematic/api/schematic/api/schematic_api/config.yml'",
E     "status": 500,
E     "title": "Internal error"
E   }
```
And also, when I ran test in `test_storage_controller_impl.py`, tests were also failing with 500 errors.

2023-07-25 19:58 UTC, andrewelamb commented
@linglp 
`No such file or directory: '/workspaces/sage-monorepo/apps/schematic/api/schematic/api/schematic_api/config.yml'`
Does this file not exist in your directory?
[config.yml](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/apps/schematic/api/schematic_api/config.yml)

2023-07-25 20:10 UTC, linglp commented
@andrewelamb The `config.yml` is there but the test is pointing at the wrong location. I think to run the test, you have to first: `cd /workspaces/sage-monorepo/apps/schematic/api`, and then `poetry run pytest schematic_api/test/test_storage_controller_endpoints.py::TestDatasets`.. This probably has something to do with how `config_handler` was written: 
```
def config_handler(asset_view: Optional[str] = None) -> None:
    """Load config file and update asset view if needed
    Args:
        asset_view (str): asset view
    """
    CONFIG.load_config(
        "../../schematic/api/schematic_api/config.yml", asset_view=asset_view
    )
```
If you change the relative path to an absolute path, I think it could avoid the error.

2023-07-25 20:13 UTC, linglp commented on apps/schematic/api/schematic_api/controllers/storage_controller_impl.py
> +    store = asset_type_object(access_token=access_token)
Thanks for sharing the design perspective. I understand it better now.. You could keep the code this way.

2023-07-25 20:18 UTC, andrewelamb commented
@linglp That config handler is going to get removed when we update to the next schematic version, as the config will be optional at that point. Since the tests are passing in CI/CD is it ok if we leave it for now?

2023-07-27 17:44 UTC, andrewelamb commented
@linglp Could you check this now? I updated Schematic to the latest version, which allowed for removal of the problematic config_handler function.

2023-08-01 16:23 UTC, linglp commented
@andrewelamb sorry for the late reply. I just got my dev container working again. When I executed `http://localhost:7081/api/v1/assetTypes/synapse/assetViews/syn23643253/projects/syn26251192/manifests` endpoint, I got an error message: 
```
{
  "detail": "The 'DATA' configuration field was accessed, but it hasn't been set yet, presumably because the schematic.CONFIG.load_config() method hasn't been run yet. Alternatively, you can re-run this code with the 'SCHEMATIC_CONFIG' environment variable set to the config.yml file, which will be automatically loaded.",
  "status": 500,
  "title": "Internal error"
}
```
I think it has something to do with not having `config.yml` in schematic. 

For simplicity, I think you could revert back to previous version of schematic and update `CONFIG.load_config` file path. After I approve, you could merge the changes you have now and create a separate PR for updating to the latest version of schematic.

2023-08-01 18:04 UTC, andrewelamb commented
@linglp I'm, pretty sure that's an error message that was removed during the configuration.py refactor in Schematic. I'm not seeing either of those errors on my local api. My guess is there's somethign wrong with your local setup, where it isn't using the latest schematic version.

2023-08-01 18:14 UTC, andrewelamb commented
@linglp

2023-08-01 22:14 UTC, andrewelamb commented
@linglp You can run `nx run prepare-python` to make sure your python packages are up to date

2023-08-02 16:40 UTC, linglp approved these changes
Approve it for now.

2023-08-02 17:25 UTC, tschaffter approved these changes

2023-08-02 17:31 UTC, merged