feat: Add /components/{componentLabel}/parents endpoint
Sage-Bionetworks/sage-monorepo pull request #1913
Opened 2023-08-03 15:40 UTC by andrewelamb

Depends on https://github.com/Sage-Bionetworks/sage-monorepo/pull/1903
fixes [fds-782](https://sagebionetworks.jira.com/browse/FDS-782)

2023-08-15 19:14 UTC, mialy-defelice requested changes
My overall comment is about the use of the terms within the descriptors and to make sure its clear what is happening and what is expected throughout. I am happy to chat about this if you want.

2023-08-15 19:14 UTC, mialy-defelice commented on libs/schematic/api-description/build/openapi.yaml
> +  /components/{componentLabel}/parents:
As noted elsewhere this is not a component specific endpoint and can be used for any node in the graph, would likely only return viable results for attributes, but if an attribute was also a valid value results would be returned if the attributes would have dependencies.

2023-08-15 19:14 UTC, mialy-defelice commented on libs/schematic/api-description/build/openapi.yaml
> +      description: Whether or not to order the components by their order in the schema, otherwise random
same comment as above, many of the things returned are actually attributes.

2023-08-15 22:20 UTC, andrewelamb commented
@mialy-defelice This is ready to re-check. Thanks!

2023-08-18 16:53 UTC, mialy-defelice requested changes

2023-08-18 16:53 UTC, mialy-defelice commented on apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
> +    """Lists the components that the input component is dependent on
this should read as "Lists the attributes that the input attribute is dependent on"

2023-08-18 16:53 UTC, mialy-defelice commented on apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
> +          The first item is either the components or an error object
substitute components for either attributes or nodes.

2023-08-18 17:02 UTC, mialy-defelice approved these changes

2023-08-18 17:02 UTC, merged