feat(ui): add text + link for truncated profile descriptions
Sage-Bionetworks/sage-monorepo pull request #1950
Opened 2023-08-09 10:16 UTC by vpchung

Fixes #1835 

## Changelog
* Add "Continue reading on ..." text for truncated descriptions

## Preview
**Profile with description <1000 characters**
![Screenshot 2023-08-09 at 2 59 42 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/5cf1a0b8-28cc-45d4-a1cc-b72b0c7e7053)

**Profile with description >1000 characters)**
![Screenshot 2023-08-09 at 2 59 47 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/75338d7f-6eab-4947-8bd0-87e5cd225822)

2023-08-14 15:12 UTC, tschaffter requested changes
- The text implies that the rest of the paragraph can be read on the challenge website. Is that always the case?
- The gray color for text should be used only for disabled elements and missing data (used recently). Having a gray link may be confusing.
- The icon should be centered vertically.

2023-08-16 16:50 UTC, rrchai commented
>The gray color for text should be used only for disabled elements and missing data (used recently). Having a gray link may be confusing.
>The text + icon is a bit too long. Can we make it shorter?

Agreed. "redirect icon" might be enough for users to understand it will be redirected to external website.

2023-08-22 14:28 UTC, tschaffter commented
> I would think so, unless you have come across an edge case for this.

If we allow external users to submit challenge descriptions like pFDA is going to do, there is no guarantee that the challenge description on OC is an excerpt that the user can continue reading on the official challenge website, in which case "continue reading" maybe not be possible.

2023-08-23 23:28 UTC, vpchung commented
@tschaffter hm. In that case, we can just be vague and just say "More details on challenge site" instead. Unless you or @rrchai have other ideas on how we can more extensive to the special cases?

2023-08-24 16:08 UTC, tschaffter commented
> we can just be vague and say "More details on challenge site" instead. 

Let's take a step back. The description of the challenge can be either:

1. Text extracted from an external source.
  a. The description has less than 1000 chars (current limit)
  b. The description has more than 1000 chars
2. Text crafted specifically for OC that meets the character limit.

In general, I believe that the user understand that they can click on the "Go to Website" button to learn more about the challenge. As such, adding a link at the end of the description that reproduce the "Go to Website" button is not required for the cases 1a and 2.

When scrapping a website - manually like we do today and later programmatically - we will extract data from sections that can easily include more than 1000 chars. Our current approach which I think is a good one is to take the first 1000 chars or so and add an ellipsis. In this case (1b), it is common to [include a “Read More” And “Continue Reading” link](https://www.smashingmagazine.com/2009/07/designing-read-more-and-continue-reading-links/).

After looking at the above article, "Read more" and "Continue reading" seem pretty standard. Compared to previously proposed solutions, they are also shorter and contribute to make the page content lighter.

"Read more" and "Continue reading" are almost equivalent. The main difference is that "Continue reading" implies that the user can resume the reading on the external site, which would be true if the content come from the external site and is up-to-date.

## Proposal

If the description ends with "...", append the link "Continue reading <external redirection icon>" that redirects to the external website. The icon is to prevent the case where the user would expect extra content to show on the OC challenge/org page when clicking on the link. The icon should be vertically centered with the text.

2023-09-18 23:01 UTC, vpchung commented
## Version 2

![Screenshot 2023-09-18 at 3 45 59 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/348e53e9-fdc8-466f-9d95-7c93f0aef81f)

2023-09-19 02:38 UTC, tschaffter requested changes
- The text is too small: small texts are more difficult to read and click.
- The icon should be vertically centered with the text: the current style makes the height of the last line different from the heights of the other lines of the paragraph.

2023-09-19 15:19 UTC, rrchai commented
<img width="270" alt="Screen Shot 2023-09-19 at 11 15 38 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/3abe6fff-ac49-4eef-a752-992a9c5c2d12">

It seems the line height is not enough - the "g" is overlapped with underline.

I may be overly picky. I now feel both capital titled "Continue Reading" or both lowercase "continue reading" is a bit more visually pleasing than "Continue reading" :)

2023-09-19 15:51 UTC, tschaffter commented
> I may be overly picky. I now personally feel both capital titled "Continue Reading" or both lowercase "continue reading" is a bit more visually pleasing than "Continue reading" :).

This [page](https://www.smashingmagazine.com/2009/07/designing-read-more-and-continue-reading-links/) includes several examples that may help making the decision.

Given that the text is very close to the paragraph, capitalizing both words may help to distinguish them form the rest of the paragraph. In the above examples, the link is often placed below the paragraph, in which case capitalizing the first letter would probably be fine.

2023-09-19 17:33 UTC, vpchung commented
> The text is too small: small texts are more difficult to read and click.

Ah, I originally changed the text size in order to differentiate it from the description.  But perhaps the color change is sufficient enough.

2023-09-19 18:07 UTC, vpchung commented
> It seems the line height is not enough - the "g" is overlapped with underline (I initially thought it was a period at the end).

Not sure if this is something we can control with the underline text-decoration?  I could perhaps do a workaround by using a border-bottom instead.

2023-09-19 19:01 UTC, rrchai commented
> Not sure if this is something we can control with the underline text-decoration?

`text-underline-offset` can do the trick, like `text-underline-offset: 3px`, but I don't think it's a must for now since it will need to adjust entire root to make underline styles consistent.

2023-09-19 19:01 UTC, rrchai commented on libs/openchallenges/challenge/src/lib/challenge-overview/challenge-overview.component.scss
> +  vertical-align: bottom;
middle maybe better?

2023-09-19 19:02 UTC, rrchai commented
either of version 3 looks good to me!

2023-09-19 20:09 UTC, vpchung commented
> `text-underline-offset`

CSS has come a long way since my web dev class... 😆

2023-09-19 21:47 UTC, vpchung commented
### Final design

![Screenshot 2023-09-19 at 2 47 11 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/e1f5232f-48ae-490a-be8c-3230956b60a2)

2023-09-19 22:02 UTC, tschaffter approved these changes
Looks great, thanks!

2023-09-19 22:16 UTC, merged