Feature fds 908 fix endpoints
Sage-Bionetworks/sage-monorepo pull request #1977
Opened 2023-08-16 16:52 UTC by andrewelamb

Depends on https://github.com/Sage-Bionetworks/sage-monorepo/pull/1918
fixes https://sagebionetworks.jira.com/browse/FDS-908

2023-08-18 16:42 UTC, mialy-defelice requested changes

2023-08-18 16:42 UTC, mialy-defelice commented on apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
> +def get_node_label_from_schematic(
There is actually another function in schematic that would figure out the node label, so this naming would probably make someone think thats what was happening here.

2023-08-18 16:42 UTC, mialy-defelice commented on apps/schematic/api/schematic_api/controllers/schema_controller_impl.py
> +def list_node_attributes(
Same comment as above this is getting the properties associate with the node or attribute.

2023-08-18 16:42 UTC, mialy-defelice commented on apps/schematic/api/schematic_api/openapi/openapi.yaml
> +  /nodes/{nodeDisplay}/nodeLabel:
Please refer to my comments in the function calls and apply changes to this file as well.

2023-08-23 17:09 UTC, andrewelamb commented
@mialy-defelice Could you re-review the changes I just made?

2023-08-25 18:39 UTC, mialy-defelice approved these changes

2023-08-25 20:09 UTC, merged