fix(ui): Move landscape metrics into top section of home page
Sage-Bionetworks/sage-monorepo pull request #2136
Opened 2023-09-18 21:20 UTC by vpchung

Sort of , kinda fixes #1836 (as discussed with @tschaffter )

## Changelog
* Replace main illustration with metrics
* Move plot of tracked challenges into the top section for more visibility
* Remove Landscape section altogether

## Preview

**Before**
![Screenshot 2023-09-18 at 2 04 42 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/449aa71e-b083-474c-981e-9794af16168c)

**After**
![Screenshot 2023-09-18 at 2 05 50 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/3e482c75-5712-4513-a025-1432e9479aa4)

**Alternative design**
![Screenshot 2023-09-18 at 2 20 28 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/1855ce3f-20ae-45ac-967a-a3265f98e739)

2023-09-19 02:35 UTC, tschaffter commented
@vpchung What are the differences between the two new designs?

2023-09-19 02:35 UTC, tschaffter commented
The unit tests are broken.

2023-09-19 15:42 UTC, rrchai requested changes

2023-09-19 15:42 UTC, rrchai commented on libs/openchallenges/home/src/lib/home.component.html
>    <openchallenges-challenge-search/>
`*sageAppShellNoRender` directive is missing.

2023-09-19 17:30 UTC, vpchung commented on libs/openchallenges/home/src/lib/challenge-search/challenge-search.component.html
> +      <div class="row text-center clickable" routerLink="/challenge">
Thanks! I must've missed this.

2023-09-19 18:30 UTC, vpchung commented on libs/openchallenges/home/src/lib/statistics-viewer/statistics-viewer.component.scss
> +// @use 'libs/openchallenges/styles/src/lib/constants';
Agreed. I didn't want to do it until the new design is agreed upon.

2023-09-19 18:51 UTC, tschaffter commented
@vpchung I would keep the title of the plot "Total Challenges Tracked", which is more concise. It's clear from the plot that it's per year. Also the "total" keyword is important so we should keep it.

The font size used for "annotated challenges" and "organizations & hosting societies" seems to small. We should be proudly state these numbers, not whisper them. ;-)

The two images next to the numbers should be bigger too.

2023-09-19 21:10 UTC, vpchung commented
Taking @tschaffter recent feedback into account, I created a couple of versions of the landing section:

### Version A
Original proposed change:

![Screenshot 2023-09-19 at 1 56 25 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/9d8adc16-8c44-4674-a3e9-ea92a4ebb48e)

### Version B
Remove metric images:

![Screenshot 2023-09-19 at 1 57 56 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/2f685b1d-f53a-4b38-830a-62a4cf7fcf3f)

### Version C
Keep magnifying glass image where it was, move metrics to a new row under the description:

![Screenshot 2023-09-19 at 2 02 48 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/3beeba7c-5dd1-4269-8e74-2b436fbfae4b)

### Version D
Remove images from the landing section altogether, keep magnifying glass image by search bar, and move metrics to a new row under the description:

![Screenshot 2023-09-19 at 2 03 48 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/ddc91a1e-8098-4ff6-ad0d-8d91d3583b3e)

2023-09-20 15:33 UTC, tschaffter commented
I have a preference for Version B because it's better structure and less dense than the other versions to me.

2023-09-21 15:25 UTC, tschaffter commented
> From our standup discussion, we will move forward with design D.

One improvement would be to move the plot title closer to the plot than to other elements.

@vpchung Could you please run this design through Adam?

2023-09-22 03:46 UTC, vpchung commented
## Final (?) version

![Screenshot 2023-09-21 at 8 41 58 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/07393b75-34a4-4b8f-981d-8104c109eb60)

FYI - @rrchai I added a negative margin-bottom to the plot title (class=`plot-title`) so that there wouldn't be as much space in-between.  I didn't see any overlap with the chart's current features, but if something does arise, that'd be the place to check first.

2023-09-22 13:12 UTC, tschaffter commented
The new design is more elegant. Similar to the previous discussion about grouping elements, the logos featuring the two persons could be moved closer to the number they illustrate. Maybe also make the labels below the number larger or bold and wrapped "organization & hosting societies" on two lines?

2023-09-22 17:23 UTC, vpchung commented
Adam's thoughts and feedback:

> I get their feedback, but I think you had it right the first time. It's valuable to have that search box near the top of the page, because that's the call to action. If I were messing around with it, trying to combine both ideas, I would try adding a metric that summarizes the graph (e.g. "215 challenges in 2023") and then pushing the full graph beneath the search area, like you have now. So, the layout would be like this:
> ![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/65b0d280-9e72-4c3f-bf9a-0d02324917da)

I'm a fan with what Adam has mocked up.  @tschaffter @rrchai @chepyle @mdsage1 your thoughts?

2023-09-22 17:52 UTC, tschaffter commented
> I'm a fan with what Adam has mocked up, maybe replace the third metric with "platforms"?

@vpchung That's a great idea and a good way to quickly introduce the three OC "core concepts".

Given this ticket and our goal to communicate on OC before the end of next week, could you ask Stockard if she could get a rush order for creating a new illustration to be displayed next to the platform number, as well as augmenting the main illustration with "biomedical, research" elements (reopening #1836 1836)?

2023-09-22 18:08 UTC, rrchai commented
> @rrchai I added a negative margin-bottom to the plot title (class=plot-title) so that there wouldn't be as much space in-between. I didn't see any overlap with the chart's current features, but if something does arise, that'd be the place to check first.

The title has default padding, but I don't see any issue using negative margin~

> I'm a fan with what Adam has mocked up, maybe replace the third metric with "platforms"?

good idea!

2023-09-25 17:45 UTC, vpchung commented
Adam shared the source of the illustrations ([unDraw](https://undraw.co/search)), and I found a couple we could use for platforms:

### Option A
![Screenshot 2023-09-25 at 10 33 38 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/061c9086-4df4-47da-a1fb-d25df3701644)


### Option B
![Screenshot 2023-09-25 at 10 33 46 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/de933d48-6a53-44ed-88f2-328d1df89d27)


### Option C
![Screenshot 2023-09-25 at 10 34 09 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4fac765c-9d6c-4119-984d-20f2df3fd847)

2023-09-25 18:15 UTC, tschaffter commented
@vpchung All the illustrations you have selected could be used to illustrate challenge platforms.

2023-09-25 18:36 UTC, vpchung commented
I personally like B the best, but it lacks a "human" in the design, so it doesn't follow the other metric illustrations.  Between A and C, I like C more.

2023-09-25 20:58 UTC, vpchung commented
> [!NOTE]  
> Closing this PR now, as the original proposed layout will not be used.  I will open a new one for [our latest iteration](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2136#issuecomment-1731781362).

2023-09-25 20:58 UTC, closed without merging