feat(ui): add platform logos to landing page
Sage-Bionetworks/sage-monorepo pull request #2148
Opened 2023-09-22 04:39 UTC by vpchung

Fixes #2144 

## Changelog 
* add "Platforms" section 
* update wording so there's a better story (see Preview)

## Preview
![Screenshot 2023-09-21 at 9 35 37 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/d0418393-5054-4ca2-83c2-8e380ca975bb)

2023-09-22 13:14 UTC, tschaffter commented
@vpchung Please create a new component instead of "hijacking" the home-organization component.

2023-09-29 00:42 UTC, tschaffter requested changes
- I would prefer to keep the "Discover Organizations" as it is now.
- The new Platform section should have a title that match the size of the title of "Discover Organizations" (no need for sub-titles)

2023-09-29 00:42 UTC, tschaffter commented on libs/openchallenges/assets/src/assets/images/platforms.svg
The image is almost 1M and is too large to be part of the app bundle and GitHub repo. The image should be placed in the S3 bucket.

2023-09-29 03:48 UTC, vpchung commented
> @tschaffter : I would prefer to keep the "Discover Organizations" as it is now.

## Option A
Section titles only

<img width="1320" alt="Screenshot 2023-09-28 at 8 40 26 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/bdad31a1-be94-482c-b8e9-465fcf0fce48">

## Option B
Section title with organization short summary

<img width="1299" alt="Screenshot 2023-09-28 at 8 43 42 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/4adeca08-0136-4667-8aa0-13a39136ecf4">

## Option C
Section title with both short summaries

<img width="1236" alt="Screenshot 2023-09-28 at 8 47 11 PM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/002dbfbe-8985-4365-b5a8-99ef8615cbd8">

2023-09-29 03:49 UTC, vpchung commented on libs/openchallenges/assets/src/assets/images/platforms.svg
Good idea.

I moved the svg to the bucket, but the image service doesn't work for me again.  So I'm not able to check if the change is correct 🙃

2023-09-29 16:53 UTC, rrchai commented
Option B looks good to me - some explanations for user can't go wrong in my opinion.

Maybe not showcasing the total number of platforms "12" here, instead using "various" or other alternatives, because it may not seem a big number for users who don't know challenge platforms.

2023-09-29 16:53 UTC, rrchai approved these changes

2023-09-29 18:08 UTC, vpchung commented
Thank you both for the feedback!  I took both of your suggestions and compromised with the following:

![Screenshot 2023-09-29 at 11 07 07 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/28d4e2c5-173e-4448-85da-bac1b4127b90)

Merging now~

2023-10-02 14:54 UTC, rrchai commented
@vpchung 

The platform image looks like this on my end:

<img width="935" alt="Screen Shot 2023-10-02 at 10 53 07 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/73901500/43f31a69-1c1e-4c55-9dba-c503c6493f20">

2023-10-02 15:10 UTC, vpchung commented
@tschaffter whenever you have time, can you review the PR again?  I'm not able to merge until you approve.

2023-10-02 15:39 UTC, tschaffter commented
I can't see how the entire Platform section looks like right now (section title + logo). Here is my feedback based on what I remember seeing during our 1:1.

If I remember correctly, the vertical space A between the title and the first row of logo is smaller than the vertical space B between rows of logos. Similarly to previous feedback, the layout would be better structured IMO if the section title was one "element" and the logos were a second "element". To achieve this, the vertical space A should be larger than B.

2023-10-02 15:40 UTC, tschaffter requested changes
I can't see how the entire Platform section looks like right now (section title + logo). Here is my feedback based on what I remember seeing during our 1:1.

If I remember correctly, the vertical space A between the title and the first row of logo is smaller than the vertical space B between rows of logos. Similarly to previous feedback, the layout would be better structured IMO if the section title was one "element" and the logos were a second "element". To achieve this, the vertical space A should be larger than B.

2023-10-02 17:47 UTC, vpchung commented
@tschaffter @rrchai I decreased the vertical padding between the frames to 5px, as well as added more padding between the image and text:

![Screenshot 2023-10-02 at 10 47 17 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/74c26457-2c54-4407-9f94-9d5f1c94d924)

2023-10-02 18:13 UTC, tschaffter commented on libs/openchallenges/home/src/lib/platforms/platforms.component.html
> +      to evaluate and compare computational algorithms.
```suggestion
      OC lists challenges from multiple platforms used by the biomedical and research community. These platforms enable participants to evaluate and compare the performance of their computational tools.
```

2023-10-02 18:24 UTC, vpchung commented
@tschaffter Thanks for the suggestion!  Here is the updated description:

![Screenshot 2023-10-02 at 11 23 36 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/5e2aa57b-a0d5-4387-8c12-85c1307ab95d)

2023-10-02 18:29 UTC, vpchung commented
Hmm... the text and image are not aligned in the center for some reason... investigating further.

2023-10-02 18:33 UTC, vpchung commented
Fixed:

![Screenshot 2023-10-02 at 11 32 57 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/28c9a58c-9597-486c-ba34-f06ed18ce767)

2023-10-02 18:44 UTC, tschaffter commented on libs/openchallenges/home/src/lib/platforms/platforms.component.html
> +      computational tools and algorithms.
Too many "and" in these two sentences?

2023-10-02 19:16 UTC, vpchung commented on libs/openchallenges/home/src/lib/platforms/platforms.component.html
> +      computational tools and algorithms.
What about:

> OC provides a catalog of various platforms used by the biomedical and research community.  These platforms enable participants to benchmark their computational tools and algorithms.

2023-10-02 19:52 UTC, tschaffter commented on libs/openchallenges/home/src/lib/platforms/platforms.component.html
> +      computational tools and algorithms.
I like this paragraph.

2023-10-02 19:53 UTC, tschaffter approved these changes

2023-10-02 20:12 UTC, merged