Fds 1605 excel endpoint
Sage-Bionetworks/sage-monorepo pull request #2748
Opened 2024-07-23 21:36 UTC by andrewelamb

2024-07-24 07:52 UTC, tschaffter commented
@andrewelamb The branch is out-of-date

2024-07-26 15:47 UTC, linglp requested changes

2024-07-26 15:47 UTC, linglp commented on apps/schematic/api/schematic_api/openapi/openapi.yaml
> +        required: true
The dataset id shouldn't be required. Users should be able to generate a a manifest in excel format without providing a dataset id

2024-07-26 15:47 UTC, linglp commented on apps/schematic/api/schematic_api/openapi/openapi.yaml
> +        required: false
here the data type should be required. Without knowing what is the data type that user wants to generate, schematic can't generate a manifest.

2024-07-26 15:47 UTC, linglp commented on apps/schematic/api/schematic_api/openapi/openapi.yaml
> +        name: useStrictValidation
I think useStrictValidation parameter is only applicable to google sheet manifest generation. You could remove it here.

2024-07-26 18:28 UTC, linglp commented
@andrewelamb is it possible to make authentication not required when user just wants to generate a new manifest with data type and no dataset id and asset view? The authentication should only be required when user is interacting with synapse. Since users don't need to interact with synapse when generating a new manifest, authentication shouldn't be required.

2024-07-26 18:33 UTC, andrewelamb commented
@linglp I'm not sure if you can or not, but I'm not aware of one since currently it's a setting at the endpoint level.

2024-07-26 18:39 UTC, andrewelamb commented
@linglp I don't think so, at least as far as I can tell its required or isn't for each endpoint. One saolution could be to split it up into two different endpoints.

2024-07-26 18:43 UTC, GiaJordan commented
> @andrewelamb is it possible to make authentication not required when user just wants to generate a new manifest with data type and no dataset id and asset view? The authentication should only be required when user is interacting with synapse. Since users don't need to interact with synapse when generating a new manifest, authentication shouldn't be required.

I agree with @linglp . The auth token should be made optional (not conditionally required) for the endpoint to match the existing behavior of the manifest generation endpoint

2024-07-26 18:48 UTC, andrewelamb commented
@GiaJordan We could make it optional, do we want to do that for both the excel and google sheet version?

2024-07-26 18:49 UTC, linglp commented
@andrewelamb I think on DCA, manifests are always generated with a dataset id and asset view. I am not sure if anyone is using schematic APIs directly to generate a new manifest. I think it makes sense to double check with @AmyHeiser and @milen-sage on: 
do we expect anyone interacting with schematic APIs to generate a manifest be able to provide a synapse token?
Currently, the people who are not on synapse can still use a schema url and a data type to generate a manifest. If we change this behavior in mono repo and always require synapse token to be present, is it going to impact anyone? 

I could approve for now. Otherwise it looks good to me.

2024-07-26 18:50 UTC, linglp approved these changes

2024-07-26 18:52 UTC, merged