Agora/migration header
Sage-Bionetworks/sage-monorepo pull request #2862
Opened 2024-09-26 23:22 UTC by sagely1

2024-09-26 23:44 UTC, sagely1 commented on libs/agora/ui/src/lib/components/footer/footer.component.html
> +        @for (item of navItems; track item.label) {
item.label is better to track

2024-09-26 23:46 UTC, sagely1 commented on libs/agora/ui/src/lib/components/header/header.component.html
> +            <!-- <gene-search class="header-search" (searchNavigated)="toggleNav()"></gene-search> -->
this will be implemented in a future PR

2024-09-27 00:00 UTC, tschaffter requested changes

2024-09-27 00:00 UTC, tschaffter commented on libs/agora/ui/src/lib/components/header/header.component.ts
> +    }
```suggestion
this.navItems = this.isMobile 
  ? [...this.defaultNavItems, ...this.mobileNavItems] 
  : [...this.defaultNavItems];
```

2024-09-27 00:06 UTC, sagely1 commented on libs/agora/ui/src/lib/components/header/header.component.ts
> +  mobileNavItems: Array<any> = [
missed this one. thanks!

2024-09-27 00:06 UTC, sagely1 commented on libs/agora/ui/src/lib/components/header/header.component.ts
> +    }
done!

2024-09-27 00:09 UTC, tschaffter approved these changes

2024-09-27 00:16 UTC, merged